version: '3.8'

services:
  api:
    image: my-api-prod
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-api-prod
    ports:
      - "${API_PORT}:3000" 
    env_file:
      - .env
    command: sh -c "pnpm prisma migrate deploy && node dist/server.js"
    restart: always
