services:
  # api:
  #   container_name: my-api-dev
  #   image: node:20.17-alpine
  #   restart: always
  #   tty: true
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgresql
  #   networks:
  #     - my_network
  #   command: >
  #     sh -c "
  #       npm install -g pnpm && 
  #       pnpm install && 
  #       pnpm dev 
  #       "

  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql-predictions-db
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=predictions-db
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - my_network

volumes:
  postgresql_data:
    driver: local

networks:
  my_network:
    driver: bridge
